// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgRZ3qSLERoolhdgMf7qdjcnGnQ8rrBlo',
    appId: '1:1033570064792:android:b95edbfe0785ff7986b3ed',
    messagingSenderId: '1033570064792',
    projectId: 'society-423fa',
    storageBucket: 'society-423fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArvQUWguSB-c5o1JFZ5O7-sYlhJCzUTv0',
    appId: '1:1033570064792:ios:3024a5b39992a79686b3ed',
    messagingSenderId: '1033570064792',
    projectId: 'society-423fa',
    storageBucket: 'society-423fa.firebasestorage.app',
    iosBundleId: 'com.example.societyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4kev902h6GYlW7TkZrEl8PDg7SOsBCxA',
    appId: '1:1033570064792:web:6a4f8c2143efa5c186b3ed',
    messagingSenderId: '1033570064792',
    projectId: 'society-423fa',
    authDomain: 'society-423fa.firebaseapp.com',
    storageBucket: 'society-423fa.firebasestorage.app',
    measurementId: 'G-0R279DN3K4',
  );
}
